- name: task level variable here...
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print the course informaiton and details
    ansible.builtin.debug:
      msg: "course name:{{course}}, duration of the course is: {{duration}}, from the trainer: {{trainer}}"