- name: lets see the variable preference...
  hosts: local
  connection: local
  vars:
    name: Hi i am play level
  vars_files:
  - preference_var_level.yaml
  vars_prompt:
  - name: name
    prompt: What is your name?
    private: false
  tasks:
  - name: testing the variable preference
    vars:
      name: i am from task level variable...
    ansible.builtin.debug:
      msg: "Name is printing: {{ name }}"

# 1st preference = command line arguments
# 2nd preference = task level
# 3rd preference = files level
# 4th preference = prompt level
# 5th preference = play level
# 6th preference = inventory level