- name: learning ansible conditions
  hosts: local
  connection: local

  vars:
    number: 5

  tasks:
    - name: Check if number is even
      ansible.builtin.debug:
        msg: "Given number {{ number }} is even"
      when: number % 2 == 0

    - name: Check if number is odd
      ansible.builtin.debug:
        msg: "Given number {{ number }} is odd"
      when: number % 2 != 0
