- name: learning functions in ansible
  hosts: local
  connection: local
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "Hello, {{ value | default('value is not defined here') }}"