- name: reading the yml and taking it into variable and storing
  hosts: local
  connection: local
  tasks:
    - name: read YAML and store in variable
      ansible.builtin.set_fact:
        student_yml: "{{ lookup('file', 'student.yml') | from_yaml }}"

    - name: convert YAML into JSON (debug)
      ansible.builtin.debug:
        msg: "{{ student_yml | to_json }}"

    - name: save JSON to file in human readable format
      ansible.builtin.copy:
        dest: ./student-data.json
        content: "{{ student_yml | to_nice_json }}"
