- name: reading the yml and taking it into varible and stored...
  hosts: local
  connection: local
  tasks:
  - name: here we can reading the yaml and storing in varible
    ansible.builtin.set_fact:
      student_yml: "{{ lookup('file', 'student.yml') | from_yaml }}"
  - name: converting yaml into json
    ansible.builtin.debug:
      msg: "{{ student_yml | to_json }}"
  - name: save json to file in human readable format 
    ansible.builtin.copy:
    dest: ./student-data.json
    content: "{{ student_yml | to_nice_json }}"