- name: creating ec2 instance and r53
  hosts: local
  connection: local
  vars:
    ami_id: "ami-09c813fb71547fc4f"
    sg_id: "sg-08fb574da3e1f9a36"   # replace with your sg id...
    zone_id: "Z01877457DKZDKQFO78G" # replace with your zone id...
    domain_name: "fineshit.shop"    # replace with your domain name here ...
    instance:
    - mongodb
    # - redis
    # - mysql
    # - rabbitmq
  tasks:
  - name: create ec2 instance...
    amazon.aws.ec2_instance:
      name: "{{item}}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id  }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instance }}"
    register: ec2_output

  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ec2_output }}"

  - name: print public_ip here...
    ansible.builtin.debug: "{{ item.instance[0].public_ip_address }}"
    loop: "{{ ec2_output.results }}"

  - name: print private_ip here...
    ansible.builtin.debug: "{{ item.instance[0].private_ip_address }}"
    loop: "{{ ec2_output.results }}"
