- name: set cart module server
  hosts: cart
  become: yes
  tasks:
  - name: disable default node module 
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable node js 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node js
    ansible.builtin.package:
      name: nodejs  
      state: present
  
  - name: create roboshop system cart
    ansible.builtin.cart:
      name: roboshop
      comment: Roboshop System cart
      system: true
      shell: /sbin/nologin
      home: /app

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent       
  
  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: delete cart file
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: download cart application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
      dest: /tmp/cart.zip

  - name: unzip the cart applicaiton
    ansible.builtin.unarchive:
       src: /tmp/cart.zip
       dest: /app
       remote_src: yes

  - name: Install packages based on package.json npm install .
    community.general.npm:
      path: /app

  - name: copy cart service file
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: cart
      enabled: true
      state: started
      daemon_reload: true

