- name: setup rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy rabbitmq repo here
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: installing rabbitmq server here
    ansible.builtin.package:
      state: present

  - name: start and enable rabbitmq server
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: create and provide permissions to user
    community.rabbitmq.rabbitmq_user:
    user: joe
    password: changeme
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present