- name: setup shipping server
  hosts: shipping
  become: yes
  tasks:
  - name: installing the maven
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql

  - name: install mysql python libraries
    ansible.builtin.pip:
      executable: pip3.9
      name: PyMySQL

  - name: create roboshop system cart
    ansible.builtin.user:
      name: roboshop
      comment: Roboshop System cart
      system: true
      shell: /sbin/nologin
      home: /app

  - name: remove app directory
    ansible.builtin.file:
      path: /app
      state: absent       
  
  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: delete shipping file
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: download shipping application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip

  - name: unzip the shipping applicaiton
    ansible.builtin.unarchive:
       src: /tmp/shipping.zip
       dest: /app
       remote_src: yes

  - name: install maven dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: moving the jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
      chdir: /app

  - name: copy shipping service file
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: import shipping mysql data into mysql
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: mysql.fineshit.shop
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql
    - /app/db/master-data.sql